
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./.docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./public:/srv/app/public:ro
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    links:
      - database
    restart: unless-stopped

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
